# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx5G
org.gradle.parallel=true

# Minecraft Properties
minecraft_version=1.21.11
minecraft_version_range=[1.21.11,26)
java_version=21

# Fabric Properties
# check these on https://fabricmc.net/develop
fabric_loader_version=0.18.3
fabric_version=0.140.0+1.21.11
loom_version=1.13-SNAPSHOT

# Mod Properties
mod_version=5.2.0
maven_group=cc.cassian.eiv
mod_id=eiv
mod_license=MIT
mod_name=EIV Canary
mod_author=2Bad4Mods, cassiancc
mod_description=A fork of the Extended Item View recipe viewer with up to date releases.
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.11-20251209.172050
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.10
parchment_version=2025.10.12

# NeoForge Properties
neoforge_version=21.11.18-beta
neoforge_version_range=[21.11,)
neoforge_loader_version_range=[1,)

mod_authors=2Bad4Mods