org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

mod.id=eiv
mod.name=EIV Canary
mod.group=de.crafty.eiv
mod.version=25.4.0
mod.description=A fork of the Extended Item View recipe viewer with up to date releases.
mod.authors=2Bad4Mods, cassiancc
mod.license=MIT

deps.fabric-loader=0.18.3

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]

publish.modrinth=
publish.curseforge=
#publish.additionalVersions=