org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true
fabric.loom.dropNonIntermediateRootMethods=true

mod.id=rrv
mod.name=Reliable Recipe Viewer (RRV)
mod.group=cc.cassian.rrv
mod.version=8.4.1
mod.description=A recipe viewer for the latest versions of Minecraft, rebuilt from EIV and designed to be configured.
mod.authors=cassiancc, 2Bad4Mods
mod.license=MIT

deps.fabric-loader=0.19.2
deps.mixin_constraints=1.0.9

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]

publish.modrinth=5VolwT6c
publish.curseforge=1422317
#publish.additionalVersions=