deps.minecraft=1.21.11
deps.minecraft_version_range=1.21.11

publish.curseforge_minecraft_version=1.21.11

deps.neoforge=21.11.44
deps.neoforge_version_range=[1.21.11,)

deps.controlify=2.5.2+1.21.11-neoforge
deps.yacl=3.8.2+1.21.11-fabric
deps.item_descriptions=2.7.2+1.21.11
deps.jade=21.1.6+fabric
deps.wthit=18.2.2
deps.jei=27.21.0.55