deps.minecraft=25w14craftmine
deps.parchment=1.21.5:2025.06.15
deps.fabric-api=0.119.10+25w14craftmine
deps.modmenu=14.0.1
deps.minecraft_version_range=>1.21.4 <1.21.6
deps.controlify=2.5.2+1.21.5-fabric
deps.yacl=3.8.2+1.21.6-fabric
deps.polymer=0.13.13+1.21.8
deps.polydex=1.6.0+1.21.6
deps.sgui=1.10.2+1.21.8
deps.placeholder=2.7.2+1.21.8
deps.predicate=0.6.0+1.21.2
deps.sidebar=0.5.1+1.21.1
deps.permissions_api=0.4.0
deps.player_data=0.8.0+1.21.6
deps.server_translations=2.5.1+1.21.5