deps.minecraft=26.2-snapshot-1
deps.minecraft_version_range=>26.1 <26.3

publish.curseforge_minecraft_version=26.2-snapshot

deps.fabric-api=0.145.4+26.2
deps.modmenu=18.0.0-alpha.8

deps.controlify=3.0.0-beta.3+26.1-fabric
deps.yacl=3.8.2+26.1.0-fabric
deps.polymer=0.16.1+26.1.1
deps.polydex=1.9.2+26.1-rc-3
deps.item_descriptions=2.7.3+26.1