deps.minecraft=26.2
deps.neoforge=26.2.0.16-beta

deps.minecraft_version_range=[26.2, 26.3)
publish.curseforge_minecraft_version=26.2

deps.controlify=3.0.0-beta.3+26.1-fabric
deps.yacl=3.9.4+26.2-neoforge
deps.polymer=0.16.1+26.1.1
deps.polydex=1.9.2+26.1-rc-3
deps.item_descriptions=2.8.1+26.2
deps.jade=26.2.0+fabric
deps.wthit=19.0.1
deps.jei=30.14.0.89