deps.minecraft=1.21.11
deps.minecraft_version_range=1.21.11

publish.curseforge_minecraft_version=1.21.11

deps.fabric-api=0.140.0+1.21.11
deps.modmenu=17.0.0-alpha.1

deps.controlify=2.5.2+1.21.11-fabric
deps.yacl=3.8.2+1.21.11-fabric
deps.polymer=0.15.2+1.21.11
deps.polydex=1.8.1+1.21.11
deps.item_descriptions=2.7.2+1.21.11
deps.jade=21.1.6+fabric
deps.wthit=18.2.2
deps.jei=27.21.0.55