deps.minecraft=26.3-snapshot-6
deps.minecraft_version_range=>26.2 <26.4

publish.curseforge_minecraft_version=26.3

deps.fabric-api=0.156.1+26.3
deps.modmenu=20.0.0-alpha.1

deps.controlify=3.0.0-beta.3+26.1-fabric
deps.yacl=3.9.4+26.1-fabric
deps.polymer=0.16.1+26.1.1
deps.polydex=1.9.2+26.1-rc-3
deps.item_descriptions=2.8.1+26.2
deps.jade=26.2.0+fabric
deps.wthit=19.0.1